version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:


volumes:
  postgres_data:
